# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'PredictY
#'
#'Gets predict y for a linear regression
#'
#'@param x,beta_hat input value
#'
#'@return y_hat
#'
#'@examples
#'mat <- matrix(c(1, 2, 3, 4, 5, 6,7,8,9), nrow = 3);
#'beta = c(1.1, 2.2, 3.3);
#'y_hat=PredictY(mat,beta);
#'
#'@export
#'
PredictY <- function(x, beta_hat) {
    .Call(`_mathcalculate_PredictY`, x, beta_hat)
}

rcpp_hello <- function() {
    .Call(`_mathcalculate_rcpp_hello`)
}

